version: 2.1

jobs:
  build:
    docker:
      - image: poifull10/ros2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: build
          command: |
            colcon build
