version: 2.1

jobs:
  build:
    docker:
      - image: poifull10/ros2
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: build-ros2
          command: |
            source /opt/ros/dashing/setup.bash
            git submodule update --init
            cd driver/WiringPi
            ./build
            cd ../../
            colcon build
